.PHONY : clean
clean:
	rm -rf ./*.svg
	rm -rf ./*.pdf
	rm -rf ./*.dot
	rm -rf *_1*
	rm -rf *_2*
	rm -rf *_3*
	rm -rf *_0*
	rm -rf *_5*
	rm -rf *_4*
	rm -rf *_6*
	rm -rf *_7*
	rm -rf *_8*
	rm -rf *_9*
